version: '3.8'

services:
  backend:
    build:
      context: .
    ports:
      - "8000:80"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 1035971912m
      DB_NAME: eficienciaproduccion
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 1035971912m
      MYSQL_DATABASE: eficienciaproduccion
      MYSQL_USER: mrfarenhate
      MYSQL_PASSWORD: 1035971912m
    volumes:
      - mysql_data:/var/lib/mysql
      - ./my.cnf:/etc/mysql/conf.d/my.cnf

volumes:
  mysql_data: